### ISSUE TITLE
Can't load table files in Doom Emacs 28.1

### ISSUE THREAD

**Issue by sableseyler** [lifelike/decide-mode#14] opened 2022-09-17 18:48 UTC
I'm getting the error `Symbol's function definition is void: remove-if-not` when I try to load a table file, and the same for `remove-if` when I try to use one. Switching to the `cl-` versions of those functions fixes it.

**Comment by lifelike** [comment] 2022-09-19 21:59
OK. Do you think the cl-versions will work elsewhere or break some other versions? I am not familiar enough with elisp to know what the implications would be, but since cl-lib is already required and some cl-functions are used I guess it would not be likely to make anything worse?

**Comment by luqtas** [comment] 2023-10-24 17:07
running a vanilla 28.2 in Debian 12 & adding the prefix 'cl-' at `remove-if-not` & `remove-if` worked for me too!

**Comment by davemq** [comment] 2024-10-13 15:32
Also broken running 30.0.91 on Fedora 40. I added

```
(require 'cl-lib)
(defalias 'remove-if-not 'cl-remove-if-not)
(defalias 'remove-if 'cl-remove-if)
```

to my init.el, restarted Emacs, and then `M-x decide-table-load-file` worked fine.

**Comment by lifelike** [comment] 2024-10-13 21:35
Unfortunately I have not seen this in any of the versions of Emacs I use, and I am not familiar enough with elisp or cl-lib to know what the best solution would be. Would happily accept some kind of fix for this. Would it be better to avoid cl-lib?

**Comment by davemq** [comment] 2024-10-14 13:19
The problem is cl-lib deprecating and renaming functions. I can see a few solutions:

- rewrite code that uses cl-lib to use something else, maybe just base Emacs Lisp
- rewrite code that uses cl-lib to use the current names, e.g. change `remove-if` to `cl-remove-if`
- add aliases at the beginning of the module, as noted above.

I don't know which of these is "best." I've dealt with a number of these cl-lib problems over a few years.

I'm willing to create a pull request to fix the parts that broke for me. I don't know if that will cover all of the cl-lib problems.

**Closed as completed** 2024-10-14 19:27 UTC
